version: '3.8'

services:
  web:
    build: .
    container_name: marking-converter
    ports:
      - "8000:8000"
    volumes:
      # Для разработки - монтируем код
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_APP=main.py
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload